# Config file version
apiVersion: 1

# List of datasources to insert/update
# Available in the database
datasources:
  - name: PostgresSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'